### ISSUE TITLE
The Paper is not available.

### ISSUE THREAD

**Issue by PengxinWang** [ChenLiu-1996/DiffusionSpectralEntropy#3]
I can't get the paper "Assessing Neural Network Representations During Training Using Noise-resilient Diffusion Spectral Entropy". 
It goes wrong when I try to get the pdf version.

**Comment by ChenLiu-1996** [comment]
Hi Mr. Wang,

Thank you for your interest. We contacted the workshop organizer to remove the previous workshop version from their website because of company policies. We are recently requesting access to publicly display this article (which I will check next week). If we got approved we will ArXiv this paper, update the paper link, and let you know.

**Comment by ChenLiu-1996** [comment]
No approval received so far. Sorry for the delay.

**Comment by PengxinWang** [comment]
That's fine, really thank you.

**Comment by ChenLiu-1996** [comment]
We have received approval for public preprint. It will be on arXiv soon. We have also put it in `https://github.com/ChenLiu-1996/DiffusionSpectralEntropy/blob/master/paper/DSE.pdf`
